FROM debian:trixie

# Install Debian packaging tools and build dependencies
RUN apt-get update && apt-get install -y \
    debhelper \
    build-essential \
    fakeroot \
    devscripts \
    lintian \
    bumpversion \
    git \
    git-lfs \
    && rm -rf /var/lib/apt/lists/* \
    && git lfs install --system --skip-repo

WORKDIR /workspace

CMD ["/bin/bash"]
