name: Publish stable release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  apt-publish:
    uses: halos-org/shared-workflows/.github/workflows/apt-publish.yml@v1.0.0-rc.1
    with:
      channel: stable
      apt-repository: hatlabs/apt.hatlabs.fi
      apt-distro: trixie
      apt-component: hatlabs
    secrets:
      APT_REPO_PAT: ${{ secrets.APT_REPO_PAT }}
